
permalink: /blog/:year/:month/:day/:title/
title: Scout Elite - Video Analysis Solutions for Youth and Minor Hockey
baseurl: ""
url: ""




plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-seo-tag
  - jekyll-sitemap
